[package]
name = "proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "*"
prost-types = "0.10.1"
tonic = "*"

[build-dependencies]
tonic-build = "*"
