[package]
name = "ffi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
cc = "1.0.71"
libloading = "0.7.0"
log = "0.4.14"
thiserror = "1.0.29"
